/* Vendors third-party runtime assets locally so the site deploys fully offline.
 * Run: node scripts/vendor-assets.mjs [--fonts] [--tiles]
 * Produces:
 *   1. Web fonts (Literata, IBM Plex Sans, JetBrains Mono) -> public/fonts/fonts.css + *.woff2
 *      Copied from the pinned `@fontsource-variable/*` devDependencies (npm), so the
 *      exact font build is locked by package-lock.json and no request to Google Fonts
 *      is ever needed — at build time or at runtime.
 *   2. CARTO dark_all basemap tiles (z6-z12, Ionian bbox) -> public/tiles/{z}/{x}/{y}.png
 * Idempotent: existing tiles are skipped; the fonts folder is rebuilt every run.
 */
import { copyFileSync, mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync, existsSync, statSync } from "fs";
import { createRequire } from "module";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const pub = join(root, "public");
const FONT_DIR = join(pub, "fonts");
const TILE_DIR = join(pub, "tiles");
const require = createRequire(import.meta.url);

/* Typography system (see src/index.css @theme):
 *   display  → Literata        (variable: wght 200–900 + opsz 7–72, true italics)
 *   body     → IBM Plex Sans   (variable: wght 100–700, italics)
 *   labels   → JetBrains Mono  (variable: wght 100–800)
 * The site is Greek-first, so every family must ship a Greek subset. */
const FONT_SOURCES = [
  { pkg: "@fontsource-variable/literata", family: "Literata", css: ["standard.css", "standard-italic.css"] },
  { pkg: "@fontsource-variable/ibm-plex-sans", family: "IBM Plex Sans", css: ["wght.css", "wght-italic.css"] },
  { pkg: "@fontsource-variable/jetbrains-mono", family: "JetBrains Mono", css: ["wght.css"] },
];
/* Unicode subsets to ship (browsers only fetch the ranges a page uses). */
const FONT_SUBSETS = ["latin-ext", "greek-ext", "latin", "greek"];

const TILE_SRC = "https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png";
const TILE_SUBDOMAINS = ["a", "b", "c", "d"];
const TILE_BBOX = { lonMin: 19.0, lonMax: 21.4, latMin: 36.3, latMax: 40.2 };
const TILE_MIN_Z = 6;
const TILE_MAX_Z = 12;
const CONCURRENCY = 8;
const RETRIES = 3;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function withRetry(fn, attempts = RETRIES) {
  for (let i = 0; i < attempts; i++) {
    try {
      return await fn();
    } catch (err) {
      if (i === attempts - 1) throw err;
      await sleep(400 * (i + 1));
    }
  }
}

async function download(url, dest, opts = {}) {
  if (opts.skipIfExists && existsSync(dest) && statSync(dest).size > 0) return false;
  const res = await withRetry(() => fetch(url, { headers: opts.headers }));
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, buf);
  return true;
}

/* ------------------------------ fonts ------------------------------ */

function vendorFonts() {
  mkdirSync(FONT_DIR, { recursive: true });
  const subsetRe = new RegExp(`-(${FONT_SUBSETS.join("|")})-`);
  const blocks = [];
  const keep = new Set(["fonts.css"]);

  for (const src of FONT_SOURCES) {
    const pkgDir = dirname(require.resolve(`${src.pkg}/package.json`));
    const meta = require(`${src.pkg}/metadata.json`);
    let count = 0;
    for (const cssFile of src.css) {
      const css = readFileSync(join(pkgDir, cssFile), "utf8");
      const re = /@font-face\s*\{[^}]+\}/g;
      let m;
      while ((m = re.exec(css)) !== null) {
        const block = m[0];
        const file = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)?.[1];
        if (!file) continue;
        const subset = file.match(subsetRe)?.[1];
        if (!subset) continue; // cyrillic / vietnamese — not needed for el/en
        copyFileSync(join(pkgDir, "files", file), join(FONT_DIR, file));
        keep.add(file);
        const local = block
          .replace(/font-family:\s*'[^']+'/, `font-family: '${src.family}'`)
          .replace(/url\(\.\/files\/([^)]+)\)/, 'url("./$1")');
        blocks.push(`/* ${src.family} · ${subset} · ${meta.version} */\n${local}`);
        count++;
      }
    }
    console.log(`  fonts: ${src.family} ${meta.version} — ${count} @font-face blocks`);
  }

  /* Drop leftovers from previous vendoring runs (e.g. other families). */
  for (const f of readdirSync(FONT_DIR)) {
    if (!keep.has(f)) unlinkSync(join(FONT_DIR, f));
  }

  const header =
    "/* Self-hosted web fonts — generated by scripts/vendor-assets.mjs from the\n" +
    "   @fontsource-variable packages pinned in package.json. Do not edit by hand. */\n\n";
  writeFileSync(join(FONT_DIR, "fonts.css"), header + blocks.join("\n\n") + "\n");
  console.log(`fonts: ${blocks.length} @font-face blocks -> public/fonts/fonts.css`);
}

/* ------------------------------ tiles ------------------------------ */

function tileXY(lon, lat, z) {
  const n = 2 ** z;
  const x = Math.floor(((lon + 180) / 360) * n);
  const latRad = (lat * Math.PI) / 180;
  const y = Math.floor(((1 - Math.log(Math.tan(latRad) + 1 / Math.cos(latRad)) / Math.PI) / 2) * n);
  return [x, y];
}

async function vendorTiles() {
  let total = 0;
  for (let z = TILE_MIN_Z; z <= TILE_MAX_Z; z++) {
    const [x0, y0] = tileXY(TILE_BBOX.lonMin, TILE_BBOX.latMax, z);
    const [x1, y1] = tileXY(TILE_BBOX.lonMax, TILE_BBOX.latMin, z);
    const jobs = [];
    for (let x = Math.max(0, x0); x <= x1; x++) {
      for (let y = Math.max(0, y0); y <= y1; y++) {
        jobs.push({ z, x, y });
      }
    }
    let done = 0;
    let skipped = 0;
    const queue = [...jobs];
    console.log(`tiles z${z}: ${jobs.length} in range`);
    async function worker() {
      while (queue.length) {
        const { z: zz, x, y } = queue.shift();
        const dest = join(TILE_DIR, String(zz), String(x), `${y}.png`);
        if (existsSync(dest)) {
          skipped++;
          continue;
        }
        const url = TILE_SRC.replace("{s}", TILE_SUBDOMAINS[Math.floor(Math.random() * TILE_SUBDOMAINS.length)])
          .replace("{z}", String(zz))
          .replace("{x}", String(x))
          .replace("{y}", String(y));
        try {
          await download(url, dest);
          done++;
          if (done % 200 === 0) console.log(`  z${zz}: ${done} downloaded`);
        } catch (err) {
          console.error(`  z${zz} ${x}/${y}: FAILED — ${err.message}`);
        }
      }
    }
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));
    total += done + skipped;
    console.log(`tiles z${z}: done, ${done} downloaded, ${skipped} cached`);
  }
  console.log(`tiles: ${total} tiles present in public/tiles`);
}

/* `--fonts` / `--tiles` limit the run to one asset class (default: both). */
const only = process.argv.slice(2).filter((a) => a.startsWith("--"));
if (!only.length || only.includes("--fonts")) vendorFonts();
if (!only.length || only.includes("--tiles")) await vendorTiles();
console.log("vendor-assets complete.");